# Databricks App Configuration for Dataverse MCP Server
# See: https://docs.databricks.com/en/dev-tools/databricks-apps/index.html

command: ["python", "-m", "server.app"]

source_code_path: "."

# Configure service principal scopes (for app's service principal)
# These are optional for Dataverse - the app primarily uses external OAuth to Dataverse
scopes:
  - "all-apis"     # Optional: Access to Databricks APIs if needed
  - "sql"          # Optional: SQL warehouses if you want to log/cache to Databricks

# Configure user authorization scopes (for on-behalf-of user calls)
# These are optional for Dataverse MCP server
user_authorization:
  scopes:
    - scope: "all-apis"
      description: "Access Databricks APIs on your behalf (optional)"

environment:
  - name: DATABRICKS_HOST
    value_from: workspace
  - name: DATABRICKS_PATH
    value_from: workspace
  - name: DATABRICKS_APP_PORT
    value_from: app_port
  - name: SERVERNAME
    value: "dataverse-mcp-server"

# ==============================================================================
# Dataverse Credentials Configuration
# ==============================================================================
#
# The app automatically reads credentials from Databricks Secrets scope 'dataverse'
# when running in Databricks Apps. No configuration needed in this file!
#
# Setup instructions:
# 1. Run: ./setup_databricks_secrets.sh
#    This creates the 'dataverse' scope and stores your credentials
#
# 2. Deploy: ./deploy.sh --create
#    The app service principal will automatically read from the secrets
#
# The code checks credentials in this order:
#   1. Environment variables (for local dev with .env.local)
#   2. Databricks Secrets scope 'dataverse' (for production)
#
# Secret keys in 'dataverse' scope:
#   - host           (DATAVERSE_HOST)
#   - tenant_id      (DATAVERSE_TENANT_ID)
#   - client_id      (DATAVERSE_CLIENT_ID)
#   - client_secret  (DATAVERSE_CLIENT_SECRET)
#
# SECURITY NOTE: Never commit actual credentials to git!
# ==============================================================================
